export {default as Login} from './Login'
export {default as NavBar} from './Navbar'
export {default as Home} from './Home'
export {default as Chat} from './Chat'
export {default as Profile} from './Profile'
export {default as Settings} from './Settings'
export {default as Friend} from './Friend'
export {default as Notif} from './Notification'