export {default as Login} from './Login'
export {default as NavBar} from './Navbar'
export {default as Chat} from './Chat'
export {default as Account} from './Account'
export {default as Friend} from './Friend'
export {default as Notif} from './Notification'
export {default as Settings} from './Settings'